### ISSUE TITLE
Request and inquire

### ISSUE THREAD

**Issue by ahmed5zake** [mindstellar/Osclass#192] opened 2020-01-30 10:37 UTC
I wanted a translation assistant to change city names .. Maybe?

------------------------------------
I use more than one language on the site, but Google only sees one language, so how do I do it until I archive the other language?

**Comment by dftd** [comment] 2020-10-14 19:27
Duplicate of https://github.com/mindstellar/Osclass/issues/27

**Closed by dftd** 2020-10-14 19:27 UTC
Labels: feature request
