### ISSUE TITLE
5.2.dev - USER_WARNING: Item is not an array or does not have the necessary variables

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#458] opened 2021-12-13 15:57 UTC
USER_WARNING: Item is not an array or does not have the necessary variables in /home/public_html/oc-includes/osclass/helpers/hDefines.php on line no 615 Error Code:512

**Comment by navjottomer** [comment] 2021-12-16 09:40
Duplicate of #446 
I changed the error message to explain what is happening in Osclass logic.

**Closed by navjottomer** 2021-12-16 09:40 UTC
Labels: bug
