### ISSUE TITLE
The "+" button on the plugin settings is inactive and it is impossible to add a new plugin

### ISSUE THREAD

**Issue by alex7070m** [mindstellar/Osclass#284] opened 2020-09-03 10:23 UTC
**Describe the bug**

Hello! After upgrading osclass from 3.8.1 to 3.9, I noticed that the "+" button on the plugin management page is inactive and I cannot add plugins. Is it possible to fix this? It would be nice if the function for adding new plugins was duplicated, for example the "add" message.

**To Reproduce**

**Expected behavior**

**Screenshots**
![03092020-plugins](https://user-images.githubusercontent.com/69157204/92103402-98349580-ede8-11ea-9592-f0f0f1d93f2e.jpg)

**Additional context**

**Comment by navjottomer** [comment] 2020-09-04 02:24
Where did you download your 3.8.1 version? BTW Plugin installing is working fine. I am not able to reproduce it.

**Comment by alex7070m** [comment] 2020-09-04 08:26
I do not remember exactly under what circumstances I had this failure, but the "+" button is not active for me. Maybe this can be fixed via phpmyadmin? What piece of code in the MySQL database is responsible for this function? What is this BTW Plugin?

**Comment by alex7070m** [comment] 2020-09-04 08:35
I have reproduced this case! if you enter a very long site title (for example  Bulletin board, dating, job. Доска объявлений, знакомства, работа в России, СНГ. 公告欄，約會，在中國工作. Tablón de anuncios, trabajo, citas. Quadro de avisos, trabalho, namoro. बुलेटिन बोर्ड, डेटिंग, भारत में काम करते हैं. 日本でデートする掲示板 )  in the main settings in the administration panel, the "+" button becomes inactive

**Comment by alex7070m** [comment] 2020-09-04 08:37
Therefore, I suggested making it possible to enter the name of the site separately for each language, so as not to enter a very long name in the old site.

**Comment by navjottomer** [comment] 2020-09-10 11:50
I couldn't reproduce the error. Plugin uploading, installing working fine, make sure to check any console error and use the support forum to get it resolved. 
BTW for multi-language preference, this can be considered in a later version but make a new issue for that.
For now, I am closing this down

**Closed by navjottomer** 2020-09-10 11:50 UTC
Labels: bug

**Comment by alex7070m** [comment] 2020-09-10 12:30
Hello! If you specify a long site title in the main settings, for example, the one I gave above
Is the "+" button still active? To reproduce this case, you need to enter the long name of the site in the main settings of the site (like the one I wrote earlier) and write again now:

Bulletin board, dating, job. Bulletin board, dating, work in Russia, CIS.公告 欄 ， 約會 ， 在 中國 工作. Tablón de anuncios, trabajo, citas. Quadro de avisos, trabalho, namoro. बुलेटिन बोर्ड, डेटिंग, भारत में काम करते हैं.日本 で デ ー ト す る 掲 示 板

What is the exact name of the plugin you are talking about? I tried searching through google for BTW plugin osclass and couldn't find it.

**Comment by navjottomer** [comment] 2020-09-10 12:44
> Is the "+" button still active? To reproduce this case, you need to enter the long name of the site in the main settings of the site (like the one I wrote earlier) and write again now:
> 
> Bulletin board, dating, job. Bulletin board, dating, work in Russia, CIS.公告 欄 ， 約會 ， 在 中國 工作. Tablón de anuncios, trabajo, citas. Quadro de avisos, trabalho, namoro. बुलेटिन बोर्ड, डेटिंग, भारत में काम करते हैं.日本 で デ ー ト す る 掲 示 板

Yes, '+' button is still active and working as intended. 
I have not talked about any plugin, I said multi-language preference can be considered in a later version for which you have to create a new issue.
